name: "Charles' Homepage"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6386a2'
    - '#00163d'
    - '#0b5095'
    - '#fefffa'
    - '#5d3c33'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
