name: "Charles' Homepage"
favicon: null
layout_spectrum: 0.17463298770599067
typography_spectrum: 0.37834457610733807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6386a2'
    - '#00163d'
    - '#0b5095'
    - '#fefffa'
    - '#5d3c33'
  brandStrength: 0.25
  lightness: 0.291032399982214
  saturation: 0.8346078030299395
  rhythmicContrast: 0.4623833990190178
purpose: []
